services:
  python:
    container_name: python-trascendence
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
  postgres:
    container_name: postgres-trascendence
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    container_name: redis-trascendence
    image: redis