FROM python:3.11.9

# Install django
RUN pip install django

#RUN pip install psycopg2-binary channels daphne channels_redis \
#				djangorestframework django-cors-headers dj-rest-auth[with_social]

#RUN pip install -r requirements.txt

CMD ["top", "-b"]